### ISSUE TITLE
Airshipper panicked.

### ISSUE THREAD

**Issue by Pheidologeton** [veloren/Airshipper#165]
Operating system: garuda linux (based on arch)
CPU: Dual xeon e5-2650v2
GPU: Nvidia gtx 1080 ti
Airshipper compiled from AUR.
I have this error:
[ERROR] Airshipper panicked: 

Error in Device::create_swap_chain: surface does not support the adapter's queue family: panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:129:9
thread 'main' panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:129:9
stack backtrace:
0:     0x563307774140 - <unknown>
1:     0x56330738147d - <unknown>
2:     0x56330778c9e4 - <unknown>
3:     0x5633077733a5 - <unknown>
4:     0x563307772a01 - <unknown>
5:     0x56330731aed8 - <unknown>
6:     0x563307772540 - <unknown>
7:     0x56330778d46d - <unknown>
8:     0x56330778d3dc - <unknown>
9:     0x56330778d38d - <unknown>
10:     0x563307190350 - <unknown>
11:     0x563307914132 - <unknown>
12:     0x563307913969 - <unknown>
13:     0x56330728a71f - <unknown>
14:     0x56330723d650 - <unknown>
15:     0x563307286d07 - <unknown>
16:     0x563307286b9c - <unknown>
17:     0x56330723d544 - <unknown>
18:     0x56330726f5be - <unknown>
19:     0x56330726c228 - <unknown>
20:     0x5633071cccc4 - <unknown>
21:     0x563307318ca1 - <unknown>
22:     0x5633072c06e9 - <unknown>
23:     0x563307239c63 - <unknown>
24:     0x5633072c03d2 - <unknown>
25:     0x7ff5ee607b25 - __libc_start_main
26:     0x5633071a3f7a - <unknown>
27:                0x0 - <unknown>
zsh: abort (core dumped)  airshipper

**Comment by Pheidologeton** [comment]
Fixed when using RUSTFLAGS="-C opt-level=3 -C target-cpu=native". When opt-level= 2 - segfail. I hope this will help someone.
