### ISSUE TITLE
Flatpak: event processor panicks with `Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }`

### ISSUE THREAD

**Issue by Gadiguibou** [veloren/Airshipper#167]
The Airshipper Flatpak crashes on startup with the following backtrace:

```
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[WARN] Missing internal features: VERTEX_STORES_AND_ATOMICS 
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
[ERROR] Airshipper panicked: 

Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }: panicked at 'Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /run/build/airshipper/cargo/vendor/winit-0.24.0/src/platform_impl/linux/x11/event_processor.rs:884:30
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /run/build/airshipper/cargo/vendor/winit-0.24.0/src/platform_impl/linux/x11/event_processor.rs:884:30
stack backtrace:
   0:     0x5652a0359ff0 - <unknown>
   1:     0x56529ff4aefc - <unknown>
   2:     0x5652a03586f4 - <unknown>
   3:     0x5652a0359095 - <unknown>
   4:     0x5652a0358abc - <unknown>
   5:     0x56529fdc20d6 - <unknown>
   6:     0x5652a03585e1 - <unknown>
   7:     0x5652a0372b6d - <unknown>
   8:     0x5652a0372adc - <unknown>
   9:     0x5652a0372a8d - <unknown>
  10:     0x56529fd24f00 - <unknown>
  11:     0x56529fd25232 - <unknown>
  12:     0x56529fed7d0c - <unknown>
  13:     0x56529fe776c7 - <unknown>
  14:     0x56529fe7747c - <unknown>
  15:     0x56529fe068a4 - <unknown>
  16:     0x56529fe697ae - <unknown>
  17:     0x56529fe65fbf - <unknown>
  18:     0x56529fdc01c5 - <unknown>
  19:     0x56529feaf379 - <unknown>
  20:     0x56529fdc68c3 - <unknown>
  21:     0x56529feaf062 - <unknown>
  22:     0x7feffc753062 - __libc_start_main
  23:     0x56529fd5bfae - <unknown>
  24:                0x0 - <unknown>
```

Can I help fix it?

**Comment by samiscool51** [comment]
not limited to flatpak's, the version installed via the ubuntu ppa also exhibits the same issue, i was able to get it to launch while using wayland on ubuntu 20.04 but when using x.org it failed. the fix in issue #166 for i3wm users might be applicable to others if they can translate `for_window [class="^airshipper$"] floating enable` into something xorg can use via it's config file.

for now use wayland if your window manager supports it until this gets fixed, if your wm doesn't, you might have to use one when you want to play temporarily until this gets fixed.
