### ISSUE TITLE
W10 crash: parent device is lost

### ISSUE THREAD

**Issue by ondras** [veloren/Airshipper#174]
Airshipper 0.7.0, installed via .msi on Windows 10. Crashes after ~3 seconds. When launched from terminal, the following is logged:

```
[INFO] Private capabilities: PrivateCapabilities { flip_y_requires_shift: true, imageless_framebuffers: true, image_view_usage: true, timeline_semaphores: true, texture_d24: false, texture_d24_s8: false, non_coherent_map_mask: 127 }
[WARN] Unrecognized device error -1009476640
[ERROR] Airshipper panicked:

Error in Queue::submit: parent device is lost: panicked at 'Error in Queue::submit: parent device is lost', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.10.1\src\backend\direct.rs:186:9
thread 'main' panicked at 'Error in Queue::submit: parent device is lost', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.10.1\src\backend\direct.rs:186:9
stack backtrace:
   0:     0x7ff7424ddb82 - <unknown>
   1:     0x7ff7420fb87a - <unknown>
   2:     0x7ff7424d2592 - <unknown>
   3:     0x7ff7424df9dc - <unknown>
   4:     0x7ff7424df748 - <unknown>
   5:     0x7ff742039e19 - <unknown>
   6:     0x7ff7424e02c3 - <unknown>
   7:     0x7ff7424e015d - <unknown>
   8:     0x7ff7424e00d9 - <unknown>
   9:     0x7ff7424e0094 - <unknown>
  10:     0x7ff74269d4d0 - <unknown>
  11:     0x7ff742073e88 - <unknown>
  12:     0x7ff74207f92a - <unknown>
  13:     0x7ff741f9d403 - <unknown>
  14:     0x7ff742034212 - <unknown>
  15:     0x7ff742031886 - <unknown>
  16:     0x7ff74203100a - <unknown>
  17:     0x7ff74204b00c - <unknown>
  18:     0x7ff742030d2a - <unknown>
  19:     0x7ff82767d3b6 - DefSubclassProc
  20:     0x7ff82767d26c - DefSubclassProc
  21:     0x7ff837f5e858 - CallWindowProcW
  22:     0x7ff837f5e3dc - DispatchMessageW
  23:     0x7ff837f70bc3 - SendMessageTimeoutW
  24:     0x7ff838bf0ba4 - KiUserCallbackDispatcher
  25:     0x7ff836271704 - NtUserDispatchMessage
  26:     0x7ff837f5e2ea - DispatchMessageW
  27:     0x7ff742033a41 - <unknown>
  28:     0x7ff74203388f - <unknown>
  29:     0x7ff74200823e - <unknown>
  30:     0x7ff742007e39 - <unknown>
  31:     0x7ff7420768c1 - <unknown>
  32:     0x7ff741fb1c1e - <unknown>
  33:     0x7ff742069960 - <unknown>
  34:     0x7ff74209be06 - <unknown>
  35:     0x7ff7420696d5 - <unknown>
  36:     0x7ff7426848e0 - <unknown>
  37:     0x7ff838767034 - BaseThreadInitThunk
  38:     0x7ff838ba2651 - RtlUserThreadStart
```

**Comment by ondras** [comment]
Seems to be fixed with recent builds.
