### ISSUE TITLE
Airshipper broken on NixOS 24.05

### ISSUE THREAD

**Issue by JackPala** [veloren/Airshipper#198]
When trying to open Airshipper on NixOS 24.05 via including the airshipper package in my list of included packages:

```
2024-06-22T02:30:44.961434Z  INFO airshipper::logger: Setup terminal and file logging. path="/home/owner/.local/share/airshipper" file="airshipper.log"
2024-06-22T02:30:44.961522Z  INFO airshipper::cli: Visit https://book.veloren.net/ for an FAQ and Troubleshooting
interface 'wl_surface' has no event 2
warning: queue 0x7f7aec000ca0 destroyed while proxies still attached:
  wl_registry@27 still attached
2024-06-22T02:30:45.150807Z  WARN wgpu_hal::gles::egl: No config found!    
2024-06-22T02:30:45.150822Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
thread '2024-06-22T02:30:45.156139Z ERROR airshipper::error: Airshipper panicked: 

WaylandSurface failed: ERROR_OUT_OF_HOST_MEMORY: panicked at /build/cargo-vendor-dir/wgpu-hal-0.12.5/src/vulkan/instance.rs:336:69:
WaylandSurface failed: ERROR_OUT_OF_HOST_MEMORY
main' panicked at /build/cargo-vendor-dir/wgpu-hal-0.12.5/src/vulkan/instance.rs:336:69:
WaylandSurface failed: ERROR_OUT_OF_HOST_MEMORY
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'airshipper' terminated by signal SIGABRT (Abort)
```

**Comment by JackPala** [comment]
Note: 
This is running Plasma 6.0 on Wayland with an RTX2060 Mobile GPU
